### ISSUE TITLE
Min age limit error in streamlit

### ISSUE THREAD

**Issue by aahnik** [bhavsarpratik/vaccine_availability#3]
![image](https://user-images.githubusercontent.com/66209958/116804895-3b88a680-ab40-11eb-95ed-c8e6d4d53a5b.png)

i set the min age limit to 18, 

so, I hope this should show all results with that min age limit. but in the results the min age limit is 45

I tried a rerun
![image](https://user-images.githubusercontent.com/66209958/116804939-77237080-ab40-11eb-83e4-7286d6314940.png)

still data not updated

**Comment by misalraj** [comment]
You have selected 'Ahmedabad' that still doesn't have for the 18-45 age group. That's why results are showing only for 45 or above.

**Comment by aahnik** [comment]
@bhavsarpratik  ya! that's perfect.

I mistakenly thought something else.

by the way, this is a fantastic project delivered in perfect time.

and after seeing this I came to know about streamlit. damn excited about it. cos, I don't know to do frontend, this will be of real help.

**Comment by ssmit-b** [comment]
@bhavsarpratik the reason user will select min age as `18+` is that they are not eligible to book slots with min age `45`.
don't you think the condition should be reversed?
